trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projects: 'Src/SocketIoClientDotNet.netstandard1.3/SocketIoClientDotNet.netstandard1.3.csproj'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: $(projects)
    arguments: '--configuration $(buildConfiguration)'


- script: |
    dotnet pack --no-build --configuration $(buildConfiguration) $(projects)
    dotnet publish --no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) $(projects)

- task: PublishBuildArtifacts@1





